spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: ${PORT:8765}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
